aliases: []
creation_timestamp: 1726212126613
current_stage: None
description: ''
last_updated_timestamp: 1726212126613
name: GNN_Mutagenicity_Best_Model
run_id: 33a1cfef715648b4909e2abdff31b24f
run_link: ''
source: /mlflow/mlruns/900649188862028013/33a1cfef715648b4909e2abdff31b24f/artifacts/best_model_fold_4
status: READY
status_message: null
storage_location: /mlflow/mlruns/900649188862028013/33a1cfef715648b4909e2abdff31b24f/artifacts/best_model_fold_4
user_id: null
version: 2
