name: streamlit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - streamlit
  - rdkit
  - pandas
  - numpy
  - seaborn
  - tqdm
  - pip
  - pip:
      - jupyterlab
      - scikit-learn
      - matplotlib
      - ogb
      - imblearn
      - torch-geometric
      - torch_optimizer
      - standardiser
      - exmol
      - skunk
      - lightning==2.0.1
      - MolVS==0.1.1
      - natsort==7.1.1
      - pyyaml==6.0.1
